version: "3.8"
services:
  apigateway:
    build: ./apiGateway
    ports:
      - "5020:80"
  inventory:
    build: ./inventory
    ports:
      - "3000:80"
  product:
    build: ./productService
    ports:
      - "5000:80"
  shopping:
    build: ./shoppingCart
    ports:
      - "7000:80"
  user:
    build: ./userService
    ports:
      - "6001:80"